version: '3.9'
services:
  web:
    build:
      context: ./server/nginx
      dockerfile: Dockerfile
    ports:
      - '${WEB_LOCAL_PORT:-8080}:${WEB_CONTAINER_PORT:-80}'
    volumes:
      - ./server/app:/var/www
      - ./server/nginx/conf.d:/etc/nginx/conf.d/
  app:
    build:
      context: ./server/app
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    env_file:
      - .env
    volumes:
      - ./server/app:/var/www

  db:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD?}
      - POSTGRES_DB=${DB_DATABASE:-postgres}
    ports:
      - '${DB_LOCAL_PORT:-5432}:${DB_CONTAINER_PORT:-5432}'

